package permissions.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import permissions.domain.Role;
import permissions.domain.Permission;

public class RoleDbManager {

    private Connection connection;
    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createRoleTable =""
            + "CREATE TABLE Permission("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY,"
            + "name VARCHAR(20),"
            + ")";

    private String insertSql ="INSERT INTO Role (name) VALUES(?)";
    private String selectSql ="SELECT * FROM PRolen";
    private String deleteSql = "DELETE FROM Role WHERE id=?";
    private String updateSql = "UPDATE Role SET (name)=(?) WHERE id=?";

    private PreparedStatement insert;
    private PreparedStatement select;
    private PreparedStatement delete;
    private PreparedStatement update;

    public RoleDbManager(){

        try {
            connection = DriverManager.getConnection(url);

            insert = connection.prepareStatement(insertSql);
            select = connection.prepareStatement(selectSql);
            delete = connection.prepareStatement(deleteSql);
            update = connection.prepareStatement(updateSql);
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);

            boolean tableExists =false;
            while(rs.next())
            {
                if(rs.getString("TABLE_NAME").equalsIgnoreCase("Role")){
                    tableExists=true;
                    break;
                }
            }

            if(!tableExists){
                Statement createTable = connection.createStatement();
                createTable.executeUpdate(createRoleTable);
            }


        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void add(Role r){

        try {
            insert.setString(1, r.getName());

            insert.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public void deleteById(int id){

        try {
            delete.setInt(1, id);
            delete.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public void update(Role o){

        try {
            update.setString(1, o.getName());
            update.setInt(3, o.getId());
            update.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }

    public List<Role> getAll(){

        List<Role> result = new ArrayList<Role>();

        try {
            ResultSet rs = select.executeQuery();
            while(rs.next()){
                Role role = new Role();
                role.setName(rs.getString("name"));
                role.setId(rs.getInt("id"));
                result.add(role);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return result;
    }

}
